version: '3.6'

services:
  user-management:
    build: user-management
    hostname: user-managementhost
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql1:
        condition: service_healthy

  mysql1:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=user-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=pwd'
      - 'MYSQL_ROOT_PASSWORD=verysecretpwd'
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  download-management:
    build: download-management
    hostname: download-managementhost
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_HOST=mongodb-download-db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=download_db
      - SPRING_DATA_MONGODB_USERNAME=download_user
      - SPRING_DATA_MONGODB_PASSWORD=download_pwd
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
    depends_on:
      mongodb-download-db:
        condition: service_healthy

  mongodb-download-db:
    image: mongo:latest
    hostname: mongodb-download-db-host
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=download_user
      - MONGO_INITDB_ROOT_PASSWORD=download_pwd
      - MONGO_INITDB_DATABASE=download_db
    volumes:
      - mongodb_download_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--norc", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  game-management:
    build: game-management
    hostname: game-managementhost
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres-game:
        condition: service_healthy

  postgres-game:
    image: 'postgres:latest'
    hostname: postgres-gamehost
    environment:
      - 'POSTGRES_DB=game-db'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=pwd'
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d game-db" ]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin_PostgreSQL
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "changeme"
    ports:
      - "5050:80"
    depends_on:
      postgres-game:
        condition: service_healthy
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    restart: always
    ports:
      - "5013:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql1
    networks:
      - default

  gateway-service:
    build: ./api-gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - user-management
      - download-management
      - game-management

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "5051:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=download_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=download_pwd
      - ME_CONFIG_MONGODB_SERVER=mongodb-download-db
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      mongodb-download-db:
        condition: service_healthy
    networks:
      - default

volumes:
  mongodb_download_data: