# This is a Spring Boot configuration file in YAML format.
# It defines settings for the application, particularly for the "prod" profile.
# Server configuration
server:
  port: 8080  # The port on which the application will run.
  #    servlet:
  #        context-path: /api  # The base path for all endpoints in the application.
  error:
    include-message: always
# Logging configuration
logging:
  level:
    root: INFO  # Default logging level for the application.
    org.springframework.web: DEBUG  # Debug-level logging for Spring web components.
    com.champsoft: TRACE  # Trace-level logging for a specific package (e.g., com.example).
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Default Spring configuration for the "prod" profile
spring:
  # Application-specific settings
  application:
    # The name of the application. Used for identification in logs and monitoring tools.
    name: user-management
  config:
    activate:
      on-profile: docker
  # DataSource configuration for connecting to the database
  datasource:
    # JDBC URL for connecting to the MySQL database.
    # Specifies the database type (mysql), host (localhost), port (3306), and database name (cardealership-db).
    # url: jdbc:mysql://localhost:3306/cardealership-db  # use this or the next statement
    url: jdbc:mysql://mysql1/user-db
    # Database username for authentication.
    username: user
    # Database password for authentication.
    password: pwd
    # JDBC driver class for MySQL. This is required for connecting to MySQL databases.
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA (Java Persistence API) configuration for database interaction
  jpa:
    # Hibernate-specific settings
    hibernate:
      # Hibernate schema generation mode.
      # "none" means no schema changes are made automatically.
      # Other options include "create", "update", "validate", etc.
      ddl-auto: none
    # Whether to log SQL statements to the console. Useful for debugging.
    show-sql: true
    # Additional properties for Hibernate
    properties:
      hibernate:
        # Whether to format SQL statements in logs for better readability.
        format_sql: true

  # SQL initialization settings
  sql:
    init:
      # Specifies the database platform (MySQL in this case).
      platform: mysql
      # Spring Boot will look for files named schema-mysql.sql and data-mysql.sql
      # rather than the generic schema-mysql.sql and data-mysql.sql.
      # Specifies when to initialize the database.
      # "always" means SQL scripts will always be executed on startup.
      mode: always
      logging:
        enabled: true