# Global settings (apply to all profiles unless overridden)
server:
  port: 8080
  error:
    include-message: always # Good for seeing error details in responses

logging:
  level:
    root: INFO
    # Keep these specific levels if you need them for debugging
    org.springframework.web: INFO # Changed from DEBUG to INFO for potentially less noise
    com.champsoft: TRACE
    org.hibernate.SQL: DEBUG # Use this to see SQL statements
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Use this to see bound parameters

spring:
  application:
    name: user-management # Global application name

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql1:3306/user-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: mysql
      mode: always
      logging:
        enabled: true

---
# src/test/resources/application-h2.yml
spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,USER # USER is a keyword in H2
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # Let JPA create the schema for each test run
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # auto-quote-keyword: true # Sometimes useful
  # If you have data.sql or schema.sql you want to run automatically (not recommended with ddl-auto: create-drop)
  # sql:
  #   init:
  #     mode: always # or embedded
  # defer-datasource-initialization: true # if using schema.sql/data.sql with ddl-auto other than 'none'