version: '3.6'

services:
  game-management:
    build: .
    hostname: game-managementhost
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=games-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=pwd'
      - 'MYSQL_ROOT_PASSWORD=verysecretpwd'
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10


  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - default


