
# ========== Default Profile ==========
server:
  port: 8080 # The Gateway itself runs on port 8080
  error:
    include-message: always
logging:
  level:
    root: INFO
    # Adjust package name if yours is different
    com.cardealership: DEBUG # Or your specific base package for verbose logging
spring:
  config:
    activate:
      on-profile: default # For running locally WITHOUT Docker
app:
  user-service:
    host: localhost # Use localhost for default profile
    port: 8081 # Exposed port for customers service
  download-service:
    host: localhost # Use localhost for default profile
    port: 8082 # Exposed port for employees service
  game-service:
    host: localhost # Use localhost for default profile
    port: 8083 # Exposed port for inventories service
---
# ========== Docker Profile ==========
spring:
  config:
    activate:
      on-profile: docker
app:
  user-service:
    host: user-management
    port: 8080
  download-service:
    host: download-management
    port: 8080
  game-service:
    host: game-management
    port: 8080
  profile-dashboard-service:
    host: profile-dashboard-service
    port: 8080

