server:
  port: 8080

spring:
  application:
    name: download-management
  data:
    mongodb:
      host: localhost
      port: 27018
      database: download_db
      username: download_user
      password: download_pwd
      authentication-database: admin
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb-download-db
      port: 27017
      database: download_db
      username: download_user
      password: download_pwd
      authentication-database: admin
      auto-index-creation: true